### ISSUE TITLE
Won't let me own door

### ISSUE THREAD

**Issue by Vnom** [LambdaGaming/Door_System#3]
When I go to own the door in game, it does not let me own it and it does not show up anything about not being able to own it in chat

**Comment by LambdaGaming** [comment]
I'm gonna need more info. Does the text come up in the center of your screen when you look at a door? What map are you using? Are there any script errors showing up in the client or server consoles? Have you verified that the addon is installed correctly?

**Comment by Vnom** [comment]
Yes, the text comes up, I am using rp_dunwood, and there are no script errors that show up in the console. I believe i installed it correctly as I put it in the addons folder.

**Comment by LambdaGaming** [comment]
Does this happen on all doors on the map or just certain ones?

**Comment by Vnom** [comment]
All doors, also I just checked the other console and an error did indeed show up.

Lua Error: [ERROR] addons/door_system-master/lua/autorun/doors_config.lua:95: attempt to call method 'getDarkRPVar' (a nil value) 1. DOOR_PRICE_CHECK - addons/door_system-master/lua/autorun/doors_config.lua:95 2. func - addons/door_system-master/lua/autorun/server/sv_doors.lua:142 3. unknown - lua/includes/extensions/net.lua:32

I believe i may have this error because I am using sandbox

**Comment by Vnom** [comment]
Actually, i'm sorry for bothering, I think i know what it may be. Thank you for the help.

**Comment by LambdaGaming** [comment]
No problem, if you're still having problems let me know.

**Comment by Vnom** [comment]
I tried, still having problems. Now i get this console error

[ERROR] addons/door_system-master/lua/autorun/client/cl_doors.lua:91: Calling net.Start with unpooled message name! [ http://goo.gl/qcx0y ]
  1. Start - [C]:-1
   2. DoClick - addons/door_system-master/lua/autorun/client/cl_doors.lua:91
    3. unknown - lua/vgui/dlabel.lua:237

**Comment by LambdaGaming** [comment]
I just checked the file and util.AddNetworkString is being called so that error shouldn't be happening. Try restarting your game/server and make sure the sv_doors.lua file is in it's correct place in lua/autorun/server/sv_doors.lua.

**Comment by Vnom** [comment]
I tried, didn't work

**Comment by LambdaGaming** [comment]
There might be another addon conflicting with this one. Run the addon on an empty server and see if it still happens.

**Comment by Vnom** [comment]
I just loaded it without any other addons, it does the same thing.

**Comment by Vnom** [comment]
Ok, I messed around a little bit more and it now works for sure, thank you for the help!
